import { useSupabaseClient, useUser } from "@supabase/auth-helpers-react";
import { type NextPage } from "next";
import Head from "next/head";
import { CreatePostWizard } from "~/components/CreatePostWizard";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data, isLoading } = api.posts.getAll.useQuery(); // runs on user's device

  const supabaseClient = useSupabaseClient();
  const user = useUser();

  async function signInWithGitHub() {
    await supabaseClient.auth.signInWithOAuth({
      provider: "github",
    });
  }

  async function signOut() {
    await supabaseClient.auth.signOut();
  }

  if (isLoading) {
    return <div>Loading...</div>;
  }

  if (!data) {
    return <div>Something went wrong...</div>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full border-x border-slate-400 bg-red-200 md:max-w-2xl">
          {!!user ? (
            <button onClick={signOut}>Sign out</button>
          ) : (
            <button onClick={signInWithGitHub}>Sign in</button>
          )}
          {!!user ? <CreatePostWizard /> : null}
          <div className=" flex flex-col">
            {data?.map(({ post, author }) => (
              <div key={post.id} className="border-b border-slate-400 p-8">
                {post.content} by {author?.username}
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
